{
 "title": "Geolocation-go",
 "description": "Metrics dashboard for Geolocation-go",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"deployment\", workload=\"geolocation-go\"}, workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"deployment\", workload=\"geolocation-go\"}, pod)"
    }
   },
   { "name": "resolution", "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  { "title": "Cumulated metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>HTTP requests metrics</span>\n</div>"
   }
  },
  {
   "title": "HTTP requests global success rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\", code=~\"^2..$\"}[$resolution])) / \nsum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\"}[$resolution]))"
    }
   ]
  },
  {
   "title": "HTTP requests volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\"}[$resolution]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Databases metrics</span>\n</div>"
   }
  },
  {
   "title": "HTTP requests response latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "HTTP requests success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{code=~\"^2..$\", path=\"/rest/v1/{ip}\"}[$resolution]))",
     "legendFormat": "Sucess requests"
    },
    {
     "expr": "sum(irate(http_requests_total{code!~\"^2..$\", path=\"/rest/v1/{ip}\"}[$resolution]))",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "In-memory cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(in_memory_items_read_total{namespace=\"$namespace\", service=\"$deployment\"}) / (sum(in_memory_items_read_total{namespace=\"$namespace\", service=\"$deployment\"}) + sum(in_memory_items_failed_read_total{namespace=\"$namespace\", service=\"$deployment\"})) * 100\n"
    }
   ]
  },
  {
   "title": "Redis cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_items_read_total{namespace=\"$namespace\", service=\"$deployment\"}) / \n(sum(redis_items_read_total{namespace=\"$namespace\", service=\"$deployment\"}) + sum(redis_items_failed_read_total{namespace=\"$namespace\", service=\"$deployment\"})) * 100\n"
    }
   ]
  },
  {
   "title": "https://ip-api/ API success hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ip_api_http_requests_success_total{namespace=\"$namespace\", service=\"$deployment\"}) / (sum(ip_api_http_requests_success_total{namespace=\"$namespace\", service=\"$deployment\"}) + sum(ip_api_http_requests_failed_total{namespace=\"$namespace\", service=\"$deployment\"})) * 100\n"
    }
   ]
  },
  {
   "title": "In-memory items counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(in_memory_items_saved_total{namespace=\"$namespace\", service=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Redis saved items counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(redis_items_saved_total{namespace=\"$namespace\", service=\"$deployment\"})"
    }
   ]
  },
  { "title": "Per pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>HTTP requests metrics</span>\n</div>"
   }
  },
  {
   "title": "HTTP requests global success rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\", code=~\"^2..$\", pod=\"$pod\"}[$resolution])) / \nsum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\", pod=\"$pod\"}[$resolution]))"
    }
   ]
  },
  {
   "title": "HTTP requests volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{namespace=\"$namespace\", service=\"$deployment\", path=\"/rest/v1/{ip}\", pod=\"$pod\"}[$resolution]))"
    }
   ]
  },
  {
   "title": "HTTP requests response latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\", path=~\"/rest/v1/{ip}\"}[$resolution])) by (le, service))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "HTTP requests success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{code=~\"^2..$\", path=\"/rest/v1/{ip}\", pod=\"$pod\"}[$resolution]))",
     "legendFormat": "Sucess requests"
    },
    {
     "expr": "sum(irate(http_requests_total{code!~\"^2..$\", path=\"/rest/v1/{ip}\", pod=\"$pod\"}[$resolution]))",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Databases metrics</span>\n</div>"
   }
  },
  {
   "title": "In-memory cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(in_memory_items_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) / (sum(in_memory_items_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) + sum(in_memory_items_failed_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"})) * 100\n"
    }
   ]
  },
  {
   "title": "Redis cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_items_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) / (sum(redis_items_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) + sum(redis_items_failed_read_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"})) * 100\n"
    }
   ]
  },
  {
   "title": "https://ip-api/ API success hits (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ip_api_http_requests_success_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) / (sum(ip_api_http_requests_success_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"}) + sum(ip_api_http_requests_failed_total{namespace=\"$namespace\", service=\"$deployment\", pod=~\"$pod\"})) * 100\n"
    }
   ]
  },
  {
   "title": "In-memory items counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "in_memory_items_saved_total{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Redis saved items counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_items_saved_total{namespace=\"$namespace\", service=\"$deployment\", pod=\"$pod\"}"
    }
   ]
  }
 ]
}