apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: geolocation-go
build:
  local:
    push: false
  artifacts:
  - image: geolocation-go
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
# Allow running unit tests before a run
test:
  - image: geolocation-go
    custom:
    - command: go test ./...
deploy:
  kubectl:
    manifests:
    - deploy/k8s/deployment.yaml
    - deploy/k8s/service.yaml
    - deploy/k8s/serviceaccount.yaml
    # If using the Prometheus operator (https://github.com/prometheus-operator/prometheus-operator),
    # uncomment to also deploy the Service Monitor
    # - deploy/k8s/servicemonitor.yaml
