apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-go
  labels:
    app: geolocation-go
spec:
  selector:
    matchLabels:
      app: geolocation-go
  template:
    metadata:
      labels:
        app: geolocation-go
    spec:
      containers:
      - name: geolocation-go
        image: geolocation-go
        env:
          - name: REDIS_CONNECTION_STRING
            value: "redis://redis:6379"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "16Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
      serviceAccountName: geolocation-go