apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: e2e-go
  name: e2e-go
spec:
  template:
    spec:
      containers:
      - image: e2e-go
        name: e2e-go
        resources: {}
        env:
          - name: NO_METRICS
            value: "true"
      restartPolicy: Never
  backoffLimit: 0