apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: e2e-go
  name: e2e-go
spec:
  template:
    spec:
      containers:
      - image: e2e-go
        name: e2e-go
        resources: {}
        # command:
        #   - "sh"
        #   - "-c"
        #   - "sleep 999999999"
        # env:
        #   - name: REDIS_CONNECTION_STRING
        #     value: redis://redis:6379
      restartPolicy: Never
  backoffLimit: 0