apiVersion: v1
kind: Pod
metadata:
  labels:
    app: e2e
  name: e2e
spec:
  containers:
  - command: ["/bin/bash", "/scripts/e2e.sh"]
    image: debian:11-slim
    name: e2e
    resources: {}
    volumeMounts:
    - name: scripts
      mountPath: /scripts
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: scripts
    configMap:
      name: e2e
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: e2e
  name: e2e
data:
  e2e.sh: |-
    #!/bin/bash

    set -x
    set -e
    set -o pipefail

    apt-get update -qq
    apt-get install -y -qq curl jq >/dev/null
    curl -v -s -q http://geolocation-go/rest/v1/1.1.1.1 | jq -C ''
    curl -v -s -q http://geolocation-go/rest/v1/2.2.2.2 | jq -C ''
    curl -v -s -q http://geolocation-go/rest/v1/3.3.3.3 | jq -C ''