apiVersion: v1
kind: Service
metadata:
  name: geolocation-go-pprof
  labels:
    app: geolocation-go
spec:
  type: ClusterIP
  selector:
    app: geolocation-go
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: pprof
    port: 6060
    protocol: TCP
    targetPort: 6060