name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: ["1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        cache: true

    - name: Build
      run: go build -v ./...
      
  test:
    strategy:
        matrix:
          version: ["1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        cache: true

    - name: Unit tests
      run: go test -v ./...

  race-condition:
    strategy:
      matrix:
        version: ["1.23", "1.24"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        cache: true
    
    - name: Test race condition
      run: go test -race -vet=off ./...